spring:
  data:
    mongodb:
      uri: mongodb://209.97.140.229:27017/testnet

server:
  port: 8080

navcoin:
  properties:
    host: 138.68.151.166
    port: 8332
    protocol: http
    username: user
    password: password
  blocksInCycle: 400

zeromq:
  address: tcp://138.68.151.166:28332

communityfund:
  blocksInCycle: 180
  minQuorum: 0.5
  proposalVoting:
    cycles: 4
    accept: 0.7
    reject: 0.7
  paymentVoting:
    cycles: 4
    accept: 0.7
    reject: 0.7